# -*- coding: utf-8 -*-
"""Capstone Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1siKps1IwNAql9dvqf1-pJj_5zHipzrhc
"""

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

dataframe = pd.read_csv(r"/content/Train_Data.csv", sep=",", encoding="unicode_escape")

dataframe.head()

dataframe.tail()

dataframe.shape

dataframe.columns

dataframe.dtypes

dataframe.describe

dataframe.nunique

#dataframe = dataframe.drop('pc', axis=1)
#sns.pairplot(dataframe)
dataframe.columns
dataframe.dtypes

count_1 = dataframe['pred'].value_counts()[1]
count_0 = dataframe['pred'].value_counts()[0]
print("Count of 1s:", count_1)
print("Count of 0s:", count_0)

test_data = pd.read_csv(r"/content/Test_Data.csv", sep=",", encoding="unicode_escape")

test_data.shape

test_data.columns

test_data.dtypes

dataframe.columns

correlation_matrix = dataframe.corr()
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=False)
plt.show()

from sklearn.svm import SVC
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from imblearn.over_sampling import RandomOverSampler
dataframe = dataframe.drop(columns=['Unnamed: 19', 'Unnamed: 20'])
dataframe = dataframe.drop(['pc', 'ma'], axis=1)
X_train = dataframe.drop('pred', axis=1)
y_train = dataframe['pred']

imputer = SimpleImputer(strategy='mean')
X_train_imputed = imputer.fit_transform(X_train)
y_train_filled = y_train.fillna(0)

oversampler = RandomOverSampler()
X_train_oversampled, y_train_oversampled = oversampler.fit_resample(X_train_imputed, y_train_filled)

# Now X_train_oversampled and y_train_oversampled contain the oversampled data
# Proceed with your model training using the oversampled data

X_train.columns

y_train.shape

dataframe.columns

dataframe.dtypes

test_data.shape

X_train_imputed_df = pd.DataFrame(X_train_imputed, columns=X_train.columns)
print(X_train_imputed_df.columns)
X_train_oversampled_df = pd.DataFrame(X_train_oversampled, columns=X_train.columns)
print(X_train_oversampled_df.columns)

from sklearn.impute import SimpleImputer
import xgboost as xgb
imputer = SimpleImputer(strategy='mean')
xgb_model = xgb.XGBClassifier()
xgb_model1 = xgb.XGBClassifier()
xgb_model.fit(X_train_imputed, y_train_filled)
xgb_model1.fit(X_train_oversampled, y_train_oversampled)

test_data.columns

test_data.dtypes

test_data = test_data.drop(["index", "pc", "ma"], axis=1)
imputer = SimpleImputer(strategy='mean')
imputer.fit(test_data)
test_data_imputed = imputer.transform(test_data)
test_data_columns = test_data.columns
test_data_imputed_df = pd.DataFrame(test_data_imputed, columns=test_data_columns)
test_data_imputed_df.columns

test_data.shape

from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
imputer.fit(X_train)
rf_model = RandomForestClassifier(n_estimators=300, max_depth=4, min_samples_split=4, min_samples_leaf=5)
rf_model.fit(X_train_oversampled, y_train_oversampled)
y_pred = rf_model.predict(test_data_imputed)

print(y_pred)

import pandas as pd
y_pred_df = pd.DataFrame(y_pred, columns=['pred'])
y_pred_df.to_csv('Capstone_hehe.csv', index=False)
